### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by pochupin**
UCS improvements

### CODE REVIEW

**Comment by smartclash** [comment]
Thank you @pochupin

**Comment by knightking10** [comment]
nice pochupin

**Comment by TrungKenbi** [comment]
Please let me join project

**Comment by knightking10** [comment]
do you know c#?

**Comment by knightking10** [comment]
you can fork this repo can create pull requests like @pochupin to contribute.
Thank you!

**Comment by TrungKenbi** [comment]
A little, I mean web programmer
I can build Web API

**Comment by knightking10** [comment]
sure.You can ask @smartclash .He is building web api.You can help him

**Comment by TrungKenbi** [comment]
I'm not good at English, but I know Vietnamese

**Comment by smartclash** [comment]
@knightking10 What? Who said i am building an API?

I am just gonna build a dashboard if anyone builds and API. **IDIOT** xD

**Comment by TrungKenbi** [comment]
Hello

**Pull request merged**
